### ISSUE TITLE
ERR RedisGraph module is currently replicating

### ISSUE THREAD

**Issue by DeoLeung** [RedisGraph/RedisGraph#2065]
```bash
127.0.0.1:6379> graph.query deo:test 'create (a:user {id:1}), (b:user {id:2}), (c:user {id:3}), (d:user {id:4}), (e:permission:template {permission: "update", template: 1}), (f:detailed {k:1}), (g:detailed {k:2}), (h:role {id:5}), (a)-[:act]->(h), (h)-[:act]->(e), (b)-[:act]->(e), (e)-[:act]->(f), (b)-[:act]->(f), (c)-[:act]->(e), (e)-[:act]->(g), (c)-[:act]->(g), (d)-[:act]->(e), (e)-[:act]->(g), (d)-[:act]->(g)'
(error) ERR RedisGraph module is currently replicating
127.0.0.1:6379> graph.list
1) permission
127.0.0.1:6379> del permission
(integer) 0
127.0.0.1:6379> graph.list
1) permission
```
hi, I have a standalone redis graph which stucking into replicating, is there a way to resume it to be usable?
I tried restart it but it's still stucking

this happens after a redis crash, normal redis is still functional, just the redis graph part is not usable

**Comment by swilly22** [comment]
Hi @DeoLeung,
Can you please share some additional information?
RedisGraph version, Redis cluster configuration, Redis version
Thank you

**Comment by DeoLeung** [comment]
I'm using the official image
```yaml
redis:
  image: redislabs/redisgraph:2.4.12
  user: "1001"
  environment:
    TZ: UTC
  ports:
    - "6379"
  entrypoint:
    - "redis-server"
    - "--databases"
    - "16"
    - "--stop-writes-on-bgsave-error"
    - "no"
    # hourly save to disk
    - "--save"
    - "3600"
    - "1"
    - "--maxmemory-policy"
    - "volatile-ttl"
    - "--aclfile"
    - "/data/user.acl"
    # redisgraph support
    - "--loadmodule"
    - "/usr/lib/redis/modules/redisgraph.so"
 ```
I keep the RDB, if needed, I can extract other information as well
