### ISSUE TITLE
redisgraph.so failed to load: libgomp.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lidaling** [RedisGraph/RedisGraph#2607]
I run reids docker docker-compose
```
version: '3.3'
services:
    redis:
      image: redis:7.0.4
      container_name: redis
      command: redis-server --requirepass 123456 --loadmodule /opt/redis-cell/libredis_cell.so --loadmodule /opt/redisgraph/redisgraph.so
        #command: redis-server /tmp/redis.conf
      ports:
        - "6379:6379"
      volumes:
        - ./data:/data
        - ./redis-cell:/opt/redis-cell
        - ./redisgraph:/opt/redisgraph
        - ./conf/redis.conf:/tmp/redis.conf

```
error message as bellow:
```
redisgraph.so failed to load: libgomp.so.1: cannot open shared object file: No such file or directory
```

and when I run make build .message show need `python2` intercepter.
